### PR TITLE
fix: Add version number to sha256 import

### LINKED ISSUE #3: sha256 is deprecated in std > 0.160.0
https://deno.land/std/hash/sha256.ts

https://github.com/dansalias/aws_s3_presign/blob/trunk/mod.ts#L1

Now returns a 404 as there is no version number published

### PR DESCRIPTION
**Pull request by mashaal**
Will fix #3

### CODE REVIEW

**Comment by Schotsl** [comment]
Merge please! :)

**Comment by mashaal** [comment]
I just moved this function into my codebase @Schotsl -- one dep and one file thankfully

**Comment by yogesnsamy** [comment]
@dansalias Will this be merged? Please advise, unable to use your module with the following error ATM: 
image

**Comment by dansalias** [comment]
Merged & deployed in `1.3.1`. Thanks for contributing!

**Pull request merged**
