### PR TITLE
Feat/add query params

### PR DESCRIPTION
**Pull request by teodorkostov-es**
* Ignore editor specific config
* Add an additional query parameters option
* Add flag that allows to use path request style

### CODE REVIEW

**Comment by dansalias** [comment]
We need an accompanying update to README.md:

`bucketName` -> `bucket`
`objectPath` -> `key`

And the addition of:
```
...
queryParams?: Record<string, string | number>  // additional query parameters
...
usePathRequestStyle?: boolean                  // use s3.amazonaws.com/<bucket>/<key> style
```

**Comment by dansalias** [comment]
@teodorkostov-es Now that we have `getHost()`, do you think that `host` is a more appropriate parameter name than `endpoint`?

**Comment by teodorkostov-es** [comment]
> @teodorkostov-es Now that we have `getHost()`, do you think that `host` is a more appropriate parameter name than `endpoint`?

Unfortunately, not. Depending on the request style the `host` is either `bucket.endpoint` or just `endpoint`. So `host` has a different meaning.

Also, the official libraries and Minio use the term `endpoint`.

**Comment by teodorkostov-es** [comment]
> We need an accompanying update to README.md:
> 
> `bucketName` -> `bucket` `objectPath` -> `key`
> 
> And the addition of:
> 
> ```
> ...
> queryParams?: Record<string, string | number>  // additional query parameters
> ...
> usePathRequestStyle?: boolean                  // use s3.amazonaws.com/<bucket>/<key> style
> ```

I have updated the `README.md` accordingly.

**Comment by teodorkostov-es** [comment]
Would you like me to add additional test cases?

**Comment by dansalias** [comment]
> > @teodorkostov-es Now that we have `getHost()`, do you think that `host` is a more appropriate parameter name than `endpoint`?
> 
> Unfortunately, not. Depending on the request style the `host` is either `bucket.endpoint` or just `endpoint`. So `host` has a different meaning.
> 
> Also, the official libraries and Minio use the term `endpoint`.

Got it, thank you.

> Would you like me to add additional test cases?

I'm happy with covering just the base case for now.

**Comment by dansalias** [comment]
Merged and deployed as `v2.0.0` as it's a breaking change to the API. https://deno.land/x/aws_s3_presign@2.0.0

Thank you very much @teodorkostov-es for contributing! I appreciate the patience (you caught me moving to a new country) and the adjustments.

**Comment by teodorkostov-es** [comment]
Thank you @dansalias. It's a great project and I was happy to contribute.

**Pull request merged**
